[project]
name = "spectral-tracker"
version = "0.1.0"
description = "Real-time neutron data assimilation"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax>=0.9.1",
    "subhkl",
]

[tool.uv.sources]
subhkl = { git = "https://github.com/neutrons/subhkl.git" }

[dependency-groups]
dev = [
    "pytest",
]
